const Exception = () => {
  return (
    <div>
      <div>
        <p>일시적인 오류가 발생했습니다.</p>
        <strong>잠시 후, 다시 시도해 주시기 바랍니다.</strong>
      </div>
    </div>
  );
};

export default Exception;
